### ISSUE TITLE
Time deltas

### ISSUE THREAD

**Issue by jseppi** [mapbox/geojson-coordinate-properties#2]
Any thoughts about supporting time deltas instead of/in addition to full-valued times?

**Comment by tmcw** [comment]
I'm not sure - it seems like full-values matches GeoJSON's existing representation of lat/lng as full values rather than deltas, and besides compression wins, it's the same data-meaning, right?

**Comment by jseppi** [comment]
Yes, that's true full times would keep more in line with GeoJSON's
coordinates.

Withdrawn.
