### ISSUE TITLE
Object for coordinateProperties?

### ISSUE THREAD

**Issue by lxbarth** [mapbox/geojson-coordinate-properties#5]
@tmcw - have you thought about using an object for `coordinateProperties` where the keys index positions in the coordinate array? It would be more verbose but would afford you the same flexibility as the regular GeoJSON `properties` hash.

```
// now: sequential (great if you have one value per coordinate)
"coordinateProperties": {
    "times": [
        1434126869275,
        1434136869275,
        1434146869275,
        1434166869275
    ]
}

// indexed (great if you have sparse values, more flexible)
"coordinateProperties":  {
        0: { "time": 1434126869275 },
        1: { "time": 1434126869275, "altitude": 312 },
        2: { "time": 1434126869275 },
        3: { "time": 1434126869275 },
}
```

**Comment by tmcw** [comment]
Your example would be

``` js
"coordinateProperties": {
    "times": [
        1434126869275,
        1434136869275,
        1434146869275,
        1434166869275
    ],
    "altitudes": [
        null,
        312,
        null,
        null
    ]
}
```

Indexed definitely does have an advantage for sparse values, but I don't see how it's more flexible.

**Comment by anandthakker** [comment]
Seems to me like the benefits for sparse values would make it worth allowing both forms in the spec.  It's a _little_ more complexity, but not tons more--both forms seem pretty natural to me.

**Comment by tmcw** [comment]
The representations are equivalent semantically - it's only a compactness benefit for very sparse data that we're discussing. I really don't know if that should be in scope of this spec - the array form is simpler to read, mirrors geojson, and compactness should be a job left to geobuf, topojson, or other formats with it as high priority.

**Comment by lxbarth** [comment]
> it's only a compactness benefit for very sparse data that we're discussing

That's right. Closing here as this was more of a question to understand the spec rather than a real world need I want to cover.
