### ISSUE TITLE
coordinateProperties on the geometry, not the feature? 

### ISSUE THREAD

**Issue by pramsey** [mapbox/geojson-coordinate-properties#6]
I find the location inside the properties a little odd, (and also, from a geometry storing database point of view, a little harder to support). This feels nicer to me:

``` json
{
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "geometry": {
            "type": "LineString",
            "coordinates": [
                [102.0, 0.0],
                [103.0, 1.0],
                [104.0, 0.0],
                [105.0, 1.0]
            ],
            "coordinateProperties": {
                "times": [
                    1434126869275,
                    1434136869275,
                    1434146869275,
                    1434166869275
                ]
            }
        },
        "properties": {
            "prop0": "value0",
            "prop1": 0.0,
        }
    }]
}
```

**Comment by tmcw** [comment]
My main concern with putting values anywhere but the `properties` object is that they aren't going to round-trip in parsers & generators - coordinateProperties in properties is just normal GeoJSON, whereas putting it in the geometry object would need parsers, databases, and generators to add a 'new thing' to their schema.

**Comment by tmcw** [comment]
Would love to hear @sgillies's take on this in particular as well as the problem of additional members that aren't in the properties object

**Comment by gendronb** [comment]
But putting `coordinateGeometries` in the geometry object would support standalone `LineString`s instead of only `Feature` objects.

**Comment by tmcw** [comment]
Sure. That's an advantage, but I consider it to be less important than round-tripping and software support.

**Comment by bhousel** [comment]
> Sure. That's an advantage, but I consider it to be less important than round-tripping and software support.

Could the proposal be that a `properties` key can appear in any GeoJSON object and is guaranteed to be ignored / preserved by software that doesn't use it?

(sorry for joining the party late, but I just discovered this project today and I want to use it for something)

**Comment by tmcw** [comment]
That's much more general than geojson-coordinate-properties, and I think it'd be much harder to get buy-in for. We're trying to define semantics for a specific property / geometry structure, but introducing properties everywhere would allow properties on a point geometry, for instance, which has no clear purpose or meaning.

**Comment by tmcw** [comment]
Closing: the scope of this issue is _supporting properties on coordinates in typical GeoJSON_. Properties on geometries are atypical and not guaranteed to roundtrip.
