### ISSUE TITLE
Support all geometry types

### ISSUE THREAD

**Issue by rouault** [mapbox/geojson-coordinate-properties#7]
GPX tracks are in fact modelled as multilinestring in case the track is stopped and resumed again (from http://www.topografix.com/gpx/1/1/gpx.xsd, a track is a list of trkseg and a "track Segment holds a list of Track Points which are logically connected in order. To represent a single GPS track where GPS reception was lost, or the GPS receiver was turned off, start a new Track Segment for each continuous span of track data"). So It might be wise to also support it.

Your proposed syntax can be easily extended for the MultiLineString case. See:

```
{
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "geometry": {
            "type": "MultiLineString",
            "coordinates": [ 
              [
                [102.0, 0.0],
                [103.0, 1.0],
                [104.0, 0.0],
                [105.0, 1.0]
              ],
              [
                [106.0,  0.0],
                [107.0,  1.0],
              ]
            ]
        },
        "properties": {
            "prop0": "value0",
            "prop1": 0.0,
            "coordinateProperties": {
                "times": [
                  [
                    1434126869275,
                    1434136869275,
                    1434146869275,
                    1434166869275
                   ],
                   [
                    1434326869275,
                    1434436869275,
                   ]
                ]
            }
        }
    }]
}
```

**Comment by tmcw** [comment]
Yep! @lbud [already proposed this in #1](https://github.com/mapbox/geojson-coordinate-properties/issues/1#issuecomment-111566063) and it seems like a good idea to support any kind of geometry, not just LineStrings. I'll retitle this issue accordingly.
